config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'featured_listings/create'
    get 'notes/filter/by_user/:id' => "notes#by_user", as: "notes_by_user"
    get 'notes/filter/by_partner/:id' => "notes#by_partner", as: "notes_by_partner"
    get "notes/filter/:filter" => "notes#index", as: "filtered_notes"
  end
  devise_scope :user do
    root to: "admin/welcome#home"
  end



  # Users
  # Using Devise RegistrationsController for public user creation/registration.
  devise_for :users, controllers: { registrations: 'registrations' }
  # Using UsersController and /users/* paths for profile viewing and editing.
  resources :users, only: [:show, :edit, :update]
  # Namespacing to the '/admin/users' path, to avoid conflicting with Devise.
  scope 'admin' do
    resources :users, only: [:index, :new, :create, :destroy]
  end

  scope 'superadmin' do
    resources :users, only: [:index, :new, :create, :destroy]
  end

  resources :partners, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :notes, only: [:index, :show, :show_images]

  namespace :admin do
    resources :partners do
      resources :notes 
    end
    resources :categories
    resources :products
    resources :notes
    resources :dietaries
    resources :procurements
    resources :values
  end

  namespace :superadmin do
    resources :partners do
      resources :notes 
    end
    resources :categories
    resources :products
    resources :notes
    resources :dietaries
    resources :procurements
    resources :values
  end

  namespace :api, constraints: { format: 'json' } do  
    namespace :v1 do
      defaults format: :json do
        resources :partners
      end
    end  
  end  

  get 'search', to: "partners#search"

  # get 'api/v1/partners', to: "api/v1/partners#index"
  # get 'api/v1/partners/:id', to: "api/v1/partners#show"
  get 'api/v1/regions', to: "api/v1/regions#index"
  get 'api/v1/category_groups', to: "api/v1/category_groups#index"
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :products
  belongs_to :featured_listings, optional: true
  has_and_belongs_to_many :dietaries
  has_and_belongs_to_many :procurements
  has_and_belongs_to_many :values
  has_many :notes
  phony_normalize :phone, default_country_code: 'US'
  has_one_attached :logo
  validates :name, presence: true, uniqueness: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, allow_blank: true
  validates :phone, phony_plausible: true
  validates :url,
    format: { with: /\Ahttps?:\/\/([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?.*/,
    message: "must be an http or https URL"},
    allow_blank: true
  validates :twitter,
    format: { with: /\Ahttps?:\/\/([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?.*/,
    message: "must be an http or https URL"},
    allow_blank: true
  validates :instagram,
    format: { with: /\Ahttps?:\/\/([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?.*/,
    message: "must be an http or https URL"},
    allow_blank: true
  validates :facebook,
    format: { with: /\Ahttps?:\/\/([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?.*/,
    message: "must be an http or https URL"},
    allow_blank: true


  def remove_all_products
      self.products.clear
  end

  def to_s
    name
  end
  
end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < ApplicationController
  before_action :restrict_unless_admin

  def index
    @partners = Partner.all.sort_by{ |partner| [ partner.name.upcase ] }
    # @note = Partner.notes
  end

  def show
    @partner = Partner.find(params[:id])
  end

  def new
    @partner = Partner.new
  end

  def edit
    @partner = Partner.find(params[:id])
  end

  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to [:admin, @partner], notice: 'Partner was successfully created.' }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @partner = Partner.find(params[:id])
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to [:admin, @partner], notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to admin_partners_url, notice: 'Partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def partner_params
      params.require(:partner).permit(:name, :longitude, :latitude, :description,
        :street_address, :city, :state, :zip, :email, :phone, :url, :logo, :email, :description,
        :hours_of_operation, :keywords, :facebook, :twitter, :instagram, product_ids: [], category_ids: [], featured_listing_ids: [] )
    end

end

app/controllers/api/v1/partners_controller.rb
class Api::V1::PartnersController < ApplicationController
    before_action :restrict_unless_admin
  
    def index
      @partners = Partner.all.sort_by{ |partner| [ partner.name.upcase ] }
    end
  
    def show
      @partner = Partner.find(params[:id])
    end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @partners = Partner.all
  end

  def show
    @partner = Partner.find(params[:id])
  end

  def search
    @partners = Partner.where("name ILIKE ?","%" + params[:q] + "%")
  end

end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/admin/partners/_form.html.haml
= form_for [:admin, @partner], multipart: true do |f|
  - if @partner.errors.any?
    #error_explanation
      %h2= "#{pluralize(@partner.errors.count, "error")} prohibited this partner from being saved:"
      %ul
        - @partner.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 10
  .form-group
    = f.label :street_address
    = f.text_field :street_address, class: 'form-control'
  .form-group
    = f.label :city
    = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :state
    = f.text_field :state, class: 'form-control'
  .form-group
    = f.label :zip
    = f.text_field :zip, class: 'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :phone
    = f.text_field :phone, class: 'form-control'
  .form-group
    = f.label :url
    = f.url_field :url, class: 'form-control'
  .form-group
    = f.label :hours_of_operation
    = f.text_field :hours_of_operation, class: 'form-control'
  .form-group
    = f.label :keywords
    = f.text_field :keywords, class: 'form-control'
  .form-group
    = f.label :latitude
    = f.number_field :latitude, class: 'form-control'
  .form-group
    = f.label :longitude
    = f.number_field :longitude, class: 'form-control'
  .form-group
    = f.label :values
    = f.text_field :values, class: 'form-control'
  .form-group
    = f.label :procurements
    = f.text_field :procurements, class: 'form-control'
  .form-group
    = f.label :dietaries
    = f.text_field :dietaries, class: 'form-control'
  .form-group
    = f.label :featured_listings
    = f.text_field :featured_listings, class: 'form-control'
  .form-group
    = f.label :facebook
    = f.text_field :facebook, class: 'form-control'
  .form-group
    = f.label :twitter
    = f.text_field :twitter, class: 'form-control'
  .form-group
    = f.label :instagram
    = f.text_field :instagram, class: 'form-control'
  .form-group
    = f.label :logo
    = f.file_field :logo, class: 'form-control-file'
  .form-group
    = f.label :products
    = f.collection_check_boxes(:product_ids, Product.all, :id, :name) do |b|
      =b.check_box + b.label(:class => "p-1")
  .form-group
    = f.label :categories
    = f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b|
      =b.check_box + b.label(:class => "p-1")
  .form-group
    = f.submit({class: 'form-control btn btn-success'})

app/views/admin/partners/edit.html.haml
.subnav
  .title
    %h1 Editing Partner

.form-container
  = render 'form'

app/views/admin/partners/index.html.haml
.subnav
  .title
    %h1 Partners
  .actions
    = link_to 'New Partner', new_admin_partner_path, class: 'primary'

%table.table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  %tbody
    - @partners.each do |partner|
      %tr
        %td= link_to partner.name, [:admin, partner]
        %td
          = link_to 'Edit', edit_admin_partner_path(partner), class: 'btn btn-sm btn-outline-primary'
          = link_to 'Delete', [:admin, partner], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' if @current_user.superadmin?

app/views/admin/partners/new.html.haml
.subnav
  .title
    %h1 New Partner

.form-container
  = render 'form'

app/views/admin/partners/show.html.haml
%div{:class => "container"}
  %div{:class => "row"}
    %div{:class => "col-sm"}
      %div{:class =>"d-flex justify-content-center"}
        =image_tag(@partner.logo, class: 'partner_logo') if @partner.logo.attached?
      %div{:class =>"d-flex justify-content-center"}
        %h1= @partner.name
      %div{:class =>"d-flex justify-content-center"}
        %i{:class => "bi-clock pr-1"}
        %p= @partner.hours_of_operation
      %div{:class =>"d-flex justify-content-center"}
        .actions
          = link_to 'Delete', [:admin, @partner], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' if @current_user.superadmin?
          = link_to 'Edit Partner', edit_admin_partner_path(@partner), class: 'btn btn-sm btn-outline-primary'
      %div{:class =>"d-flex justify-content-center text-center"}
        %dd.col-sm-9= @partner.description
      %div{:class =>"d-flex justify-content-center"}
      %div{:class =>"d-flex justify-content-center text-center"}
      %div{:class =>"d-flex justify-content-center"}
        = button_to @partner.facebook, {class: 'btn btn-small', :disabled => !@partner.facebook.present?, :form => {target: '_blank'}} do
          %i{:class => "m-2 bi bi-facebook fa-lg", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Link to partner Facebook"}
        = button_to @partner.instagram, {class: 'btn btn-small', :disabled => !@partner.instagram.present?, :form => {target: '_blank'}} do
          %i{:class => "m-2 bi bi-instagram fa-lg", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Link to partner Instagram"}
        = button_to @partner.twitter, {class: 'btn btn-small', :disabled => !@partner.twitter.present?, :form => {target: '_blank'}} do
          %i{:class => "m-2 bi bi-twitter fa-lg", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Link to partner twitter"}
      %div{:class => "container"}
        %div{:class => "row d-flex justify-content-center pt-1"}
          %button{:class => "btn border btn-light btn-block rounded-pill w-60", :onclick => "copytoclipboard(); this.innerHTML='Copied!", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Search address in Google maps"}
            = link_to "#{@partner.street_address} #{@partner.city}, #{@partner.state} #{@partner.zip}", "http://www.google.com/maps?ie=UTF-8&q=#{@partner.street_address} #{@partner.city}, #{@partner.state} #{@partner.zip}", target: :_blank
            %i{:class => "bi-map pl-1"}
        %div{:class => "row d-flex justify-content-center pt-1"}
          %button{:class => "btn border btn-light btn-block rounded-pill w-60", :onclick => "copytoclipboard(); this.innerHTML='Copied!", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Send an email"}
            = mail_to @partner.email
            %i{:class => "bi-envelope pl-1"}
        %div{:class => "row d-flex justify-content-center pt-1"}
          %button{:class => "btn border btn-light btn-block rounded-pill w-60", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Go to partner website"}
            = link_to "#{@partner.url}", @partner.url, target: :_blank
            %i{:class => "bi-link-45deg pl-1"}
        %div{:class => "row d-flex justify-content-center pt-1"}
          %button{:class => "btn border btn-light btn-block rounded-pill w-60", :data-toggle => "tooltip", :data-placement => "bottom", :title =>"Partner phone"}
            = "#{@partner.phone}".phony_formatted(normalize: :NA, format: :national, spaces: ' ')
            %i{:class => "bi-telephone pl-1"}
 
      %br
      %dt.col-sm-3 Categories
      %dd.col-sm-9
        - @partner.categories.each do |category|
          .row-sm-9= link_to category.name, [:admin, category]
      %dt.col-sm-3 Featured Listing
      %dd.col-sm-9
        .row-sm-9= featured_listing_name(@partner.featured_listing_id)
      %dt.col-sm-3 Dietary
      %dd.col-sm-9
        - @partner.dietaries.each do |dietary|
          .row-sm-9= dietary.name
      %dt.col-sm-3 Procurement
      %dd.col-sm-9
        - @partner.procurements.each do |procurement|
          .row-sm-9= procurement.name
      %dt.col-sm-3 Values
      %dd.col-sm-9
        - @partner.values.each do |value|
          .row-sm-9= value.name
      %dt.col-sm-3 Discount
      %dd.col-sm-9= @partner.discount

    %div{:class => "col-sm border rounded bg-light"}
      %div{:class => "d-flex pt-2"}
        %div{:class => "p-2"}
          %h3 Notes
        %div{:class => "ml-auto p-2"}
          %button{:class => "btn btn-outline-dark rounded-circle", :id => "notebutton", :data-toggle => "tooltip", :data-placement => "bottom", :title => "Add a new note"}+
          -# = button_tag "", id: "notebutton", :class => "bi-plus-circle" 
        
          #notesform
            = form_for [:admin, @partner, Note.new] do |f|
              .form-group
                = f.label :title
                = f.text_field :title, :required => true, class: 'form-control'
              .form-group
                = f.text_area :body, :required => true, class: 'form-control', rows: 8 
              .form-group
                =f.file_field :images, class: 'form-control'
              .form-group
                = f.submit({class: 'form-control btn btn-success'})
                -#= button_tag 'Submit', type: 'submit', class: "btn btn-primary"
      %div{:class => "container overflow-auto mt-4", :style => "height: 500px;"}
        - @partner.notes.each do |note|
          %div{:class => "card"}
            %div{:class => "card-header"}
              = link_to note.title, [:admin, note]
              last edited #{date_time(note)} 
            / .actions= link_to 'View Body', "note-body" => "#{note.body}"
            %div{:class => "card-body"}  
              %dl.row{:id => "bodybutton"}View Body
              %dl.row.a{:id => "notebody"}#{note.body} 
              / %dl.row.actions= link_to "Delete Note", [:admin, @partner, Note.delete(note.id)], id: "notedelete", class: "btn btn-primary", data: { confirm: "Are you sure?" }