config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'featured_listings/create'
    get 'notes/filter/by_user/:id' => "notes#by_user", as: "notes_by_user"
    get 'notes/filter/by_partner/:id' => "notes#by_partner", as: "notes_by_partner"
    get "notes/filter/:filter" => "notes#index", as: "filtered_notes"
  end
  devise_scope :user do
    root to: "admin/welcome#home"
  end



  # Users
  # Using Devise RegistrationsController for public user creation/registration.
  devise_for :users, controllers: { registrations: 'registrations' }
  # Using UsersController and /users/* paths for profile viewing and editing.
  resources :users, only: [:show, :edit, :update]
  # Namespacing to the '/admin/users' path, to avoid conflicting with Devise.
  scope 'admin' do
    resources :users, only: [:index, :new, :create, :destroy]
  end

  scope 'superadmin' do
    resources :users, only: [:index, :new, :create, :destroy]
  end

  resources :partners, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :notes, only: [:index, :show, :show_images]

  namespace :admin do
    resources :partners do
      resources :notes 
    end
    resources :categories
    resources :products
    resources :notes
    resources :dietaries
    resources :procurements
    resources :values
  end

  namespace :superadmin do
    resources :partners do
      resources :notes 
    end
    resources :categories
    resources :products
    resources :notes
    resources :dietaries
    resources :procurements
    resources :values
  end

  namespace :api, constraints: { format: 'json' } do  
    namespace :v1 do
      defaults format: :json do
        resources :partners
      end
    end  
  end  

  get 'search', to: "partners#search"

  # get 'api/v1/partners', to: "api/v1/partners#index"
  # get 'api/v1/partners/:id', to: "api/v1/partners#show"
  get 'api/v1/regions', to: "api/v1/regions#index"
  get 'api/v1/category_groups', to: "api/v1/category_groups#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :partners
  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :restrict_unless_admin

  def index
    @categories = Category.all.sort_by{ |category| [ category.name.upcase ] }
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id]) 
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
= form_for [:admin, @category] do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit({class: 'form-control btn btn-success'})

app/views/admin/categories/edit.html.haml
.subnav
  .title
    %h1 Editing Category

.form-container
  = render 'form'

app/views/admin/categories/index.html.haml
.subnav
  .title
    %h1 Categories
  .actions
    = link_to 'New Category', new_admin_category_path, class: 'primary'

%table.table
  %thead
    %tr
      %th Category
      %th
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.name, [:admin, category]
        %td
          = link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-sm btn-outline-primary'
          = link_to 'Delete', [:admin, category], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' if @current_user.superadmin?

app/views/admin/categories/new.html.haml
.subnav
  .title
    %h1 New Category

.form-container
  = render 'form'

app/views/admin/categories/show.html.haml
.subnav
  .title
    %h1= @category.name
  .actions
    = link_to 'Delete', [:admin, @category], method: :delete, data: { confirm: 'Are you sure?' }, class: 'danger' if @current_user.superadmin?
    = link_to 'Edit', edit_admin_category_path(@category), class: 'primary'

%table.table
  %thead
    %tr
      %th Partners
      %th
  %tbody
    - @category.partners.each do |partner|
      %tr
        %td= link_to partner.name, [:admin, partner]
        %td
  