config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'featured_listings/create'
    get 'notes/filter/by_user/:id' => "notes#by_user", as: "notes_by_user"
    get 'notes/filter/by_partner/:id' => "notes#by_partner", as: "notes_by_partner"
    get "notes/filter/:filter" => "notes#index", as: "filtered_notes"
  end
  devise_scope :user do
    root to: "admin/welcome#home"
  end



  # Users
  # Using Devise RegistrationsController for public user creation/registration.
  devise_for :users, controllers: { registrations: 'registrations' }
  # Using UsersController and /users/* paths for profile viewing and editing.
  resources :users, only: [:show, :edit, :update]
  # Namespacing to the '/admin/users' path, to avoid conflicting with Devise.
  scope 'admin' do
    resources :users, only: [:index, :new, :create, :destroy]
  end

  scope 'superadmin' do
    resources :users, only: [:index, :new, :create, :destroy]
  end

  resources :partners, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :notes, only: [:index, :show, :show_images]

  namespace :admin do
    resources :partners do
      resources :notes 
    end
    resources :categories
    resources :products
    resources :notes
    resources :dietaries
    resources :procurements
    resources :values
  end

  namespace :superadmin do
    resources :partners do
      resources :notes 
    end
    resources :categories
    resources :products
    resources :notes
    resources :dietaries
    resources :procurements
    resources :values
  end

  namespace :api, constraints: { format: 'json' } do  
    namespace :v1 do
      defaults format: :json do
        resources :partners
      end
    end  
  end  

  get 'search', to: "partners#search"

  # get 'api/v1/partners', to: "api/v1/partners#index"
  # get 'api/v1/partners/:id', to: "api/v1/partners#show"
  get 'api/v1/regions', to: "api/v1/regions#index"
  get 'api/v1/category_groups', to: "api/v1/category_groups#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :partners
  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :restrict_unless_admin
  
    def index
      @products = Product.all.sort_by{ |product| [ product.name.upcase ] }
    end
  
    def show
      @product = Product.find(params[:id])
    end
  
    def new
      @product = Product.new
    end
  
    def edit
      @product = Product.find(params[:id])
    end
  
    def create
      @product = Product.new(product_params)
  
      respond_to do |format|
        if @product.save
          format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      @product = Product.find(params[:id])
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
  
      def product_params
        params.require(:product).permit(:name)
      end
      
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!

    def index
      @products = Product.all
    end
  
    def show
      @product = Product.find(params[:id])
    end
  
  end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
= form_for [:admin, @product] do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit({class: 'form-control btn btn-success'})

app/views/admin/products/edit.html.haml
.subnav
  .title
    %h1 Editing Product

.form-container
  = render 'form'

app/views/admin/products/index.html.haml
.subnav
  .title
    %h1 Products
  .actions
    = link_to 'New Product', new_admin_product_path, class: 'primary'

%table.table
  %thead
    %tr
      %th Product
      %th
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, [:admin, product]
        %td
          = link_to 'Edit', edit_admin_product_path(product), class: 'btn btn-sm btn-outline-primary'
          = link_to 'Delete', [:admin, product], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' if @current_user.superadmin?

app/views/admin/products/new.html.haml
.subnav
  .title
    %h1 New Product

.form-container
  = render 'form'

app/views/admin/products/show.html.haml
.subnav
  .title
    %h1= @product.name
  .actions
    = link_to 'Delete', [:admin, @product], method: :delete, data: { confirm: 'Are you sure?' }, class: 'danger' if @current_user.superadmin?
    = link_to 'Edit', edit_admin_product_path(@product), class: 'primary'

%table.table
  %thead
    %tr
      %th Partners
      %th
  %tbody
    - @product.partners.each do |partner|
      %tr
        %td= link_to partner.name, [:admin, partner]
        %td